### PR TITLE
Add abstract test class for initialization strategy

### PR DESCRIPTION
**Pull request by Croshiw**
In order to test the gaussians initialization in the superclass, ` initializeMeanVectorsFor: numberOfGaussians:` should be implemented in the kmeans strategy.
For the meanvectors initialization, maybe it should be done in each subclass

### CODE REVIEW

**Comment by jordanmontt** [comment]
I forgot to add the gitattributes file so When I look at files changed I see 10 classes that have been changed. Can you tell me exactly what you have added/modified please?

**Comment by jordanmontt** [comment]
I think it is better to close this PR. I will add the gitattributes files and then you can re-do the Pr. Is it that ok for you? @Croshiw

**Comment by Croshiw** [comment]
okey @jordanmontt

**Comment by jordanmontt** [comment]
Ok, I added the normalized line endings. Please re-do the PR

**Pull request closed without merging**
